from falcon.tabular.processors.scaler_and_encoder import ScalerAndEncoder
from falcon.tabular.processors.label_decoder import LabelDecoder
from falcon.tabular.processors.multi_modal_encoder import MultiModalEncoder