[build-system]

requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "skl2onnx>=1.17.0,<1.19.0",
    "scikit-learn>=1.5.0,<1.7.0",
    "numpy>=1.18.0,<3.0.0",
    "onnx>=1.16.0,<2.0.0",
    "pandas>=1.0.0,<3.0.0",
    "imbalanced-learn>=0.8.1,<1.0.0",
    "pyarrow>=12.0.0",
    "optuna>=3.0.0,<5.0.0",
]

name = "falcon-ml"
version = "0.8.0"
authors = [
  { name="Oleh Kostromin", email="oleh@beastbyte.ai" },
  { name="Iryna Kondrashchenko", email="iryna@beastbyte.ai" },
]
description = "AutoML library for fast experementations."
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
runtime = ["fnnx[core]>=0.0.3,<0.1.0"]


[tool.pytest.ini_options]
pythonpath = [
  "."
]