"""Rendering the C header that carries the string tables out of the compiled graph."""

from __future__ import annotations

import textwrap
from collections.abc import Iterable, Sequence

from falcon.codegen.graph import CategoricalMapping, StringMapping

_HEADER = """/* {prefix}_falcon.h -- generated by falcon {version}; do not edit.
 *
 * Companion to `{prefix}.h`, which holds the compiled model itself. C has no string
 * tensor, so the categorical features reach `{prefix}_run()` as int64 category codes
 * and, for classification, the prediction comes back as an int64 class index. This
 * header is where the strings went: one table per categorical feature, plus the class
 * labels, and the lookups that move between them.
 *
 * Usage -- define the implementation macro in exactly one translation unit:
 *
 *     #define {upper}_FALCON_IMPLEMENTATION
 *     #include "{prefix}_falcon.h"
 *
 * {prefix}_run() takes its inputs in this order:
 *
{inputs}
 *
 * and writes these outputs:
 *
{outputs}
 */

#ifndef {upper}_FALCON_H_INCLUDED
#define {upper}_FALCON_H_INCLUDED

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Returned for a value that is in no category. The model was fitted with
 * `handle_unknown="ignore"`, so an unseen category contributes an all-zero encoding
 * rather than failing. */
#define {upper}_FALCON_UNKNOWN_CATEGORY (-1)

"""

_FOOTER = """
#ifdef __cplusplus
}}
#endif

#endif /* {upper}_FALCON_H_INCLUDED */

#ifdef {upper}_FALCON_IMPLEMENTATION
#ifndef {upper}_FALCON_IMPLEMENTATION_INCLUDED
#define {upper}_FALCON_IMPLEMENTATION_INCLUDED

#include <string.h>

{implementations}
#endif /* {upper}_FALCON_IMPLEMENTATION_INCLUDED */
#endif /* {upper}_FALCON_IMPLEMENTATION */
"""

_ENCODE_BODY = """int64_t {symbol}(const char* value)
{{
    if (value == NULL{missing_test}) {{
        return {missing_code};
    }}
    for (int64_t index = 0; index < {count}; index++) {{
        if (strcmp(value, {symbol}_categories[index]) == 0) {{
            return index;
        }}
    }}
    return {upper}_FALCON_UNKNOWN_CATEGORY;
}}
"""

_LABEL_BODY = """const char* {prefix}_class_label(int64_t index)
{{
    if (index < 0 || index >= {macro}) {{
        return NULL;
    }}
    return {prefix}_class_labels[index];
}}
"""


def render_helper(
    prefix: str,
    mapping: StringMapping,
    *,
    version: str,
    inputs: Sequence[tuple[str, str, str]],
    outputs: Sequence[tuple[str, str]],
) -> str:
    """Render `<prefix>_falcon.h`.

    `inputs` are `(c_name, c_type, description)` triples and `outputs` `(c_name, c_type)`
    pairs, both taken from the compiler's own report so that the signature documented in
    the header is the one the artifact actually has.
    """
    upper = prefix.upper()
    sections = [
        _HEADER.format(
            prefix=prefix,
            upper=upper,
            version=version,
            inputs=_comment_list(
                f"{c_name} ({c_type}) -- {note}" for c_name, c_type, note in inputs
            ),
            outputs=_comment_list(f"{c_name} ({c_type})" for c_name, c_type in outputs),
        )
    ]
    implementations: list[str] = []

    for categorical in mapping.categoricals:
        symbol = f"{prefix}_encode_{categorical.name}"
        sections.append(_declare_categorical(symbol, categorical))
        implementations.append(_define_categorical(symbol, upper, categorical))

    if mapping.class_labels:
        macro = f"{upper}_FALCON_CLASS_COUNT"
        sections.append(_declare_labels(prefix, macro, mapping.class_labels))
        table = _string_table(
            f"const char* const {prefix}_class_labels[{macro}]", mapping.class_labels
        )
        implementations.append(
            f"{table}\n{_LABEL_BODY.format(prefix=prefix, macro=macro)}"
        )

    sections.append(
        _FOOTER.format(upper=upper, implementations="\n".join(implementations))
    )
    return "".join(sections)


def _declare_categorical(symbol: str, categorical: CategoricalMapping) -> str:
    macro = f"{symbol.upper()}_COUNT"
    sentences = [
        f"`{categorical.name}` ({categorical.column_type}): "
        f"{len(categorical.categories)} categories, in the order the model indexes them."
    ]
    if categorical.imputed:
        filled = (
            f"category {categorical.missing_code} "
            f"(`{categorical.categories[categorical.missing_code]}`)"
            if categorical.missing_code >= 0
            else "no category, giving an all-zero encoding"
        )
        tokens = ", ".join(f"`{token}`" for token in categorical.missing_tokens)
        sentences.append(
            f"A missing value -- NULL or {tokens} -- was filled during training and "
            f"maps to {filled}."
        )
    else:
        sentences.append(
            "The model was trained without imputation, so a missing value is an "
            "ordinary category if it was seen during training and unknown otherwise."
        )
    return (
        f"{_block_comment(sentences)}\n"
        f"#define {macro} {len(categorical.categories)}\n"
        f"extern const char* const {symbol}_categories[{macro}];\n"
        f"int64_t {symbol}(const char* value);\n\n"
    )


def _define_categorical(
    symbol: str, upper: str, categorical: CategoricalMapping
) -> str:
    macro = f"{symbol.upper()}_COUNT"
    table = _string_table(
        f"const char* const {symbol}_categories[{macro}]", categorical.categories
    )
    missing_test = "".join(
        f" || strcmp(value, {_quote(token)}) == 0"
        for token in categorical.missing_tokens
    )
    encode = _ENCODE_BODY.format(
        symbol=symbol,
        upper=upper,
        count=macro,
        missing_code=(
            categorical.missing_code
            if categorical.imputed
            else f"{upper}_FALCON_UNKNOWN_CATEGORY"
        ),
        missing_test=missing_test,
    )
    return f"{table}\n{encode}"


def _declare_labels(prefix: str, macro: str, labels: Sequence[str]) -> str:
    return (
        "/* The target's class labels, indexed by the `y_pred` class index the model\n"
        " * returns. */\n"
        f"#define {macro} {len(labels)}\n"
        f"extern const char* const {prefix}_class_labels[{macro}];\n"
        f"const char* {prefix}_class_label(int64_t index);\n\n"
    )


def _string_table(declaration: str, values: Iterable[str]) -> str:
    entries = ",\n".join(f"    {_quote(value)}" for value in values)
    return f"{declaration} = {{\n{entries}\n}};\n"


def _quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = "".join(
        character if 0x20 <= ord(character) < 0x7F else _escape(character)
        for character in escaped
    )
    return f'"{escaped}"'


def _escape(character: str) -> str:
    if character in "\n\r\t":
        return {"\n": "\\n", "\r": "\\r", "\t": "\\t"}[character]
    return "".join(f"\\{byte:03o}" for byte in character.encode())


def _comment_list(entries: Iterable[str]) -> str:
    return "\n".join(f" *     {entry}" for entry in entries)


def _block_comment(sentences: Sequence[str]) -> str:
    lines = textwrap.wrap(" ".join(sentences), width=84)
    body = "\n".join(f" * {line}" for line in lines[1:])
    return f"/* {lines[0]}\n{body}\n */" if body else f"/* {lines[0]} */"
